<!DOCTYPE html>
<html lang="hu">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Egyszerű Weboldal</title>
    <style>
        /* Beépített CSS stílusok */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            background-color: #f0f0f0;
        }

        h1 {
            color: #333;
            margin: 0;
        }

        p {
            color: #666;
            margin: 10px 0;
        }

        button {
            padding: 10px 20px;
            font-size: 16px;
            color: #fff;
            background-color: #007bff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>Üdvözöllek az oldalon!</h1>
    <p>Ez egy teljesen működő, egyszerű weboldal.</p>
    <button onclick="greetUser()">Kattints ide!</button>

    <script>
        // Beépített JavaScript funkció
        function greetUser() {
            alert("Helló! Köszönöm, hogy ellátogattál erre az oldalra!");
        }

        console.log("Az oldal betöltődött.");
    </script>
</body>
</html>

    
